name: capture output
on: workflow_dispatch
jobs:
  # Output from step
  #   setup:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Set debug
  #         id: set-debug-state
  #         run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

  #       - name: Get stage
  #         run: echo "The build stage is ${{ steps.set-debug-state.outputs.BUILD_STAGE }}"

  setup:
    runs-on: ubuntu-latest

    outputs:
      build-stage: ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}

    steps:
      - name: Set debug
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

    #   report:
    #     runs-on: ubuntu-latest
    #     needs: setup
    #     steps:
    #       - name: Get stage
    #         run: echo "The build stage is ${{ needs.setup.outputs.build-stage }}"

  report:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get stage
        env:
          BUILD_STAGE: ${{ needs.setup.outputs.build-stage }}
        run: echo "The build stage is $BUILD_STAGE"
